=== oripapo123/projects/Realestate/Assignement3 spl/Assets.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Assets">
    <xs:annotation>
      <xs:documentation>&lt;Assets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Assets.xsd"></xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Asset" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Name"/>
              <xs:element type="xs:string" name="Type"/>
              <xs:element type="xs:byte" name="Size"/>
              <xs:element name="Location">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:byte" name="x" use="optional"/>
                      <xs:attribute type="xs:byte" name="y" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:byte" name="CostPerNight"/>
              <xs:element name="AssetContents">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="AssetContent" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Name"/>
                          <xs:element type="xs:float" name="RepairMultiplier"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== oripapo123/projects/Realestate/Assignement3 spl/Assets.xml
<?xml version="1.0" encoding="utf-8"?>
<!--  
<Assets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Assets.xsd">
-->
<Assets>
	<Asset>
		<Name>Asset 1</Name>
		<Type>Apartment</Type>
		<Size>3</Size>
		<Location x = "20" y = "20" />
		<CostPerNight>100</CostPerNight>
		<AssetContents>
			<AssetContent>
				<Name>TV</Name>
				<RepairMultiplier>5</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Bed</Name>
				<RepairMultiplier>8</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Fridge</Name>
				<RepairMultiplier>3</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Desk</Name>
				<RepairMultiplier>4</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Stove</Name>
				<RepairMultiplier>3.5</RepairMultiplier>
			</AssetContent>
		</AssetContents>
	</Asset>
	<Asset>
		<Name>Asset 2</Name>
		<Type>Loft</Type>
		<Size>5</Size>
		<Location x = "20" y = "25" />
		<CostPerNight>30</CostPerNight>
		<AssetContents>
			<AssetContent>
				<Name>TV</Name>
				<RepairMultiplier>2.5</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Fridge</Name>
				<RepairMultiplier>2</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Desk</Name>
				<RepairMultiplier>1.5</RepairMultiplier>
			</AssetContent>
		</AssetContents>
	</Asset>
	<Asset>
		<Name>Asset 3</Name>	
		<Type>Hut</Type>
		<Size>3</Size>
		<Location x = "15" y = "21" />
		<CostPerNight>25</CostPerNight>
		<AssetContents>
			<AssetContent>
				<Name>TV</Name>
				<RepairMultiplier>1</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Bed</Name>
				<RepairMultiplier>2</RepairMultiplier>
			</AssetContent>
		</AssetContents>
	</Asset>
	<Asset>
		<Name>Asset 4</Name>
		<Type>House</Type>
		<Size>5</Size>
		<Location x = "20" y = "15" />
		<CostPerNight>50</CostPerNight>
		<AssetContents>
			<AssetContent>
				<Name>TV</Name>
				<RepairMultiplier>5</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Bed</Name>
				<RepairMultiplier>1</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Fridge</Name>
				<RepairMultiplier>1.5</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Desk</Name>
				<RepairMultiplier>2.5</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Stove</Name>
				<RepairMultiplier>3.75</RepairMultiplier>
			</AssetContent>
		</AssetContents>
	</Asset>
	<Asset>
		<Name>Asset 5</Name>	
		<Type>Cottage</Type>
		<Size>5</Size>
		<Location x = "12" y = "16"/>
		<CostPerNight>120</CostPerNight>
		<AssetContents>
			<AssetContent>
				<Name>TV</Name>
				<RepairMultiplier>2.5</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Bed</Name>
				<RepairMultiplier>1.65</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Fridge</Name>
				<RepairMultiplier>1.25</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Desk</Name>
				<RepairMultiplier>5.5</RepairMultiplier>
			</AssetContent>
			<AssetContent>
				<Name>Stove</Name>
				<RepairMultiplier>4.75</RepairMultiplier>
			</AssetContent>
		</AssetContents>
	</Asset>
</Assets>
